name: Deploy Backend to Local Network VPS

on:
  push:
    branches:
      - guidance-deploy
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file inside frontend folder
        run: echo "${{ secrets.ENV_FILE_C }}" > ./backend/.env

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD_C }}" | docker login -u "${{ secrets.DOCKER_USERNAME_C }}" --password-stdin

      - name: Build & push backend image
        run: |
          cd backend
          docker build -t chamindunipun99/guidance-backend:latest .
          docker push chamindunipun99/guidance-backend:latest

      - name: Deploy to Local Network VPS (10.50.227.121)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 10.50.227.182
          username: deieprj
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd ~/ai
            docker-compose pull backend
            docker-compose up -d backend
